# Generated by Django 2.1.2 on 2018-10-04 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('homepage', models.URLField(blank=True)),
                ('engine', models.CharField(blank=True, max_length=20)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gameinfo.Developer')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('shortName', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_released', models.DateField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.Game')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gameinfo.Platform')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(choices=[('youtube.com', 'Youtube'), ('metacritic.com', 'Metacritic'), ('en.wikipedia.org', 'Wikipedia')])),
                ('url', models.URLField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.Game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='gameinfo.Genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gameinfo.Publisher'),
        ),
        migrations.AddField(
            model_name='game',
            name='releases',
            field=models.ManyToManyField(through='gameinfo.Release', to='gameinfo.Platform'),
        ),
    ]
