# Generated by Django 2.1.2 on 2018-10-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='releases',
        ),
        migrations.RemoveField(
            model_name='release',
            name='platform',
        ),
        migrations.AddField(
            model_name='release',
            name='platform',
            field=models.ManyToManyField(to='gameinfo.Platform'),
        ),
    ]
