# Generated by Django 2.1.2 on 2018-10-04 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0002_auto_20181004_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='platform',
            new_name='platforms',
        ),
    ]
